.Dd March 14, 2021
.Dt CAUSAL.AGENCY 7
.Os "Causal Agency"
.
.Sh NAME
.Nm june
.Nd computer enthusiast!!
.
.Sh SYNOPSIS
.Nm mail
.Mt june@causal.agency
.Nm
in
.Li #ascii.town
on freenode
.
.Sh DESCRIPTION
I make mostly IRC software in C.
I like
.Fx
and
.Ox
but also the GPL.
I want to learn to talk to strangers
and seek out as much magic as I can.
.
.Pp
.Lk https://git.causal.agency code
\(em
.Lk https://text.causal.agency words
.Pq Lk gopher://text.causal.agency gopher
\(em
.Lk /list/ mailist
\(em
.Lk https://liberapay.com/june/ liberapay
.
.Pp
These are some things I've done:
.Bl -tag -width Ds
.It Lk https://git.causal.agency/pounce/about pounce
a multi-client-first IRC bouncer
.It Lk https://git.causal.agency/catgirl/about catgirl
a cosy IRC client
.It Lk https://git.causal.agency/litterbox/about litterbox
a full-text search IRC logger
.It Lk https://git.causal.agency/scooper/about scooper
a web interface for litterbox
.It Lk https://git.causal.agency/catsit/about catsit
a process supervisor
.It Lk https://git.causal.agency/imbox/about "imbox & git-fetch-email"
a tool to pull patches out of IMAP
.It Lk https://git.causal.agency/bubger/about bubger
a mailing list archive generator for IMAP
.It Lk https://git.causal.agency/notemap/about notemap
a tool to mirror text files to IMAP notes
.It Lk https://ascii.town/explore.html torus@ascii.town
a collaborative ASCII art project
.It Lk ssh://play@ascii.town play@ascii.town
a 2048 and snake game over
.Xr ssh 1
.It Lk https://git.causal.agency/cards/about cards
a
.Pa CARDS.DLL
loader for SDL
.It Lk scheme.png scheme
an earthy terminal colour scheme
.El
.
.Sh SEE ALSO
.Lk /bin/ bin
