.Dd April 18, 2024
.Dt CAUSAL.AGENCY 7
.Os "Causal Agency"
.
.Sh NAME
.Nm june
.Nd computer enthusiast (she/her)
.
.Sh SYNOPSIS
.Nm mail
.Mt june@causal.agency
.Nm
in
.Li #ascii.town
on tilde.chat
.
.Sh DESCRIPTION
I make mostly IRC software in C.
I like
.Ox
but also the GPL.
I just want to read books
and try to learn to be kinder.
When I can I'd like to talk to strangers
and experience more magic.
.
.Pp
.Lk https://git.causal.agency code
\(em
.Lk https://text.causal.agency words
\(em
.Lk https://photo.causal.agency photos
\(em
.Lk /list/ mailist
.
.Pp
These are some things I've done:
.Bl -tag -width Ds
.It Lk https://git.causal.agency/pounce/about pounce
a multi-client-first IRC bouncer
.It Lk https://git.causal.agency/catgirl/about catgirl
a cosy IRC client
.It Lk https://git.causal.agency/litterbox/about litterbox
a full-text search IRC logger
.It Lk https://git.causal.agency/scooper/about scooper
a web interface for litterbox
.It Lk https://git.causal.agency/kitd/about kitd
a process supervisor
.It Lk https://git.causal.agency/imbox/about "imbox & git-fetch-email"
a tool to pull patches out of IMAP
.It Lk https://git.causal.agency/bubger/about bubger
a mailing list archive generator for IMAP
.It Lk https://git.causal.agency/notemap/about notemap
a tool to mirror text files to IMAP notes
.It Lk https://ascii.town/explore.html torus@ascii.town
a collaborative ASCII art project
.It Lk ssh://play@ascii.town play@ascii.town
some games to play over
.Xr ssh 1
.It Lk https://git.causal.agency/cards/about cards
a
.Pa CARDS.DLL
loader for SDL
.It Lk scheme.png scheme
an earthy terminal colour scheme
.El
.
.Sh SEE ALSO
.Bl -bullet
.It
.Lk /bin/ bin
.It
.Lk lands.html "Magic lands quiz"
.It
.Lk alpha.html "alphabet ranking game"
.El
