.Dd July 26, 2023
.Dt LEVELER 7
.Os "Causal Agency"
.
.Sh NAME
.Nm Leveler
.Nd A Magic: The Gathering\(tm Game Format
.
.Sh DECK CONSTRUCTION
A full deck of 100 cards consists of 3 sub-decks:
.Pp
.Bl -enum -offset indent -compact
.It
50 cards
.It
30 cards
.It
20 cards
.El
.
.Pp
A full deck may contain only one of each card other than basic lands.
.
.Pp
Cards from all Magic sets are legal,
except those
.Lk https://magic.wizards.com/en/banned-restricted-list#legacy-banned "banned in the Legacy format" ,
as well as:
.Pp
.Bl -bullet -offset indent -compact
.It
.Lk https://scryfall.com/card/thb/73/thassas-oracle "Thassa's Oracle"
.It
.Lk https://scryfall.com/card/uma/61/laboratory-maniac "Laboratory Maniac"
.It
.Lk https://scryfall.com/card/war/54/jace-wielder-of-mysteries "Jace, Wielder of Mysteries"
.It
.Lk https://scryfall.com/card/40k/46/out-of-the-tombs "Out of the Tombs"
.It
.Lk https://scryfall.com/card/jmp/13/ormos-archive-keeper "Ormos, Archive Keeper"
.El
.
.Sh PLAY RULES
Each player starts the game with 30 life.
.
.Pp
Each player starts the game
with their first sub-deck in their library.
The two other sub-decks are outside of the game.
.
.Pp
When a player's library is empty,
if one of their sub-decks
is still outside the game,
their next sub-deck enters the game
and is shuffled into their library.
This is a state-based action.
.
.Pp
When a player has taken 10 total damage
over the course of the game,
if their second sub-deck is outside the game,
they exile their library.
This is a state-based action.
.
.Pp
When a player has taken 20 total damage
over the course of the game,
if their third sub-deck is outside the game,
they exile their library.
This is a state-based action.
.
.Sh AUTHORS
.An June McEnroe Aq Mt june@causal.agency
