.Dd March 16, 2022
.Dt TOUR 7
.Os "Causal Agency"
.
.Sh NAME
.Nm tour
.Nd things that are here
.
.Sh FILES
.Bl -tag -width Ds
.It Pa home/
.Dq dotfiles
.It Pa bin/
utilities of varying utility
.It Pa doc/rfc/
scripts for reading IETF RFCs
.It Pa doc/zlib/
zlib documentation ported to
.Xr mdoc 7
.It Pa www/
sources for causal.agency sites
.El
