#!/bin/sh

# PROVIDE: samba_mdns
# REQUIRE: samba_server mdnsd
# KEYWORD: shutdown

. /etc/rc.subr

name="samba_mdns"
rcvar="samba_mdns_enable"

load_rc_config $name

: ${samba_mdns_enable:="NO"}
: ${samba_mdns_name:="${hostname}"}
: ${samba_mdns_port:="445"}
: ${samba_mdns_text:=""}

procname="/usr/local/sbin/mdnsctl"
command="/usr/sbin/daemon"
pidfile="/var/run/${name}.pid"

publish_args="${samba_mdns_name} smb tcp ${samba_mdns_port} '${samba_mdns_text}'"
command_args="-T mdnsctl -p ${pidfile} -- ${procname} publish ${publish_args}"

run_rc_command "$1"
