.Dd January 12, 2024
.Dt GIT.CAUSAL.AGENCY 7
.Os "Causal Agency"
.
.Sh NAME
.Nm causal agency
.Nd \(dqI think some people from the Gentoo project are behind this.\(dq
.
.Sh DESCRIPTION
basically cgit (awful software)
getting hammered by web crawlers
keeps making my machine crash.
this static page will be here
until I can find a better solution.
clone urls and tarball urls are still functional.
