.Dd November 26, 2020
.Dt INABILITY 7
.Os "Causal Agency"
.
.Sh NAME
.Nm Inability
.Nd losing the ability to create
.
.Sh DESCRIPTION
For often weeks, sometimes months at a time,
I lose the ability to write new code.
I can still make fixes
and little cleanups
in my existing projects,
but if I try to work on something new,
nothing happens.
I can't get anything done.
.
.Pp
I think it's now been
over 3 months
since I've created anything.
I don't know what to do about it.
In the past I've eventually
regained the ability to code,
but it's unclear to me how or why.
I also don't know what
I should be doing instead.
Writing code is the only hobby
I've ever really developed,
so without it I basically
don't do anything.
.
.Pp
Does this happen to anyone else?
How do you cope?
.
.Sh AUTHORS
.Mt june@causal.agency
