.Dd May  5, 2021
.Dt SWANS-ARE-DEAD 7
.Os "Causal Agency"
.
.Sh NAME
.Nm Swans Are Dead
.Nd album by Swans
.
.Sh DESCRIPTION
Swans Are Dead
is the best Swans album.
Among my favourites are
Soundtracks for the Blind,
To Be Kind
and Love of Life,
but Swans Are Dead
is the one I come back to
most consistently.
I'm always in the mood
to listen to these tunes.
.
.Pp
It's interesting to me
that I enjoy it so much,
I think because I had the expectation
that live albums
are not of the same quality
as studio albums,
but that's just completely untrue
in the case of Swans.
The performances are excellent
and the recording is
for the most part perfect.
The album feels live,
without any distracting deficiencies
of live recording
that would take you out
of just enjoying the music.
.
.Bl -ohang
.It Dq Feel Happiness
This track feels kind of special
since it's the only song on the album
that was never released
as part of another project.
I absolutely love this format of song.
It's like 10 minutes of build
before any lyrics happen,
which you only get after
the wave of the first part
of the song collapses.
It bookends the first disc nicely with
.Dq Blood Promise,
I think,
which is sort of the reverse.
.
.It Dq Blood On Yr Hands
This is such a great start
to the Jarboe-focused
section of the black disc.
A cappella apart from the hum
of the equipment on stage,
I love this vocal performance.
I sing this song,
terribly,
in the shower.
The lack of instrumental
seems to make it stick in my mind even more.
.
.It Dq I Crawled
This is another great vocal performance
by Jarboe.
It's so much more dynamic and intense
than the version of this song
released much earlier on Young God
with Gira's vocals.
I remember seeing a bad comment
somewhere online
from someone who couldn't stand
any Swans song Jarboe sang on.
They must have never heard
this version of
.Dq I Crawled.
Incredible.
.
.It Dq Blood Promise
My favourite track on
Swans Are Dead,
by far.
I had actually never heard of
.Dq The Whiffenpoof Song
until I looked up
the recording they use
to introduce this song
and indicate it's the last of the show.
Anyway,
this track highlights
what makes Swans live albums
so interesting.
This performance of the song
has evolved so much
from the studio recording on
The Great Annihilator.
They share the same lyrics,
but the earlier version is only 4:15,
to the live version's fifteen and a half minutes!
And it sucks me in the whole time.
As the song winds down
you can hear an audience member yell,
.Dq Don't stop!
and I agree.
.
.It Dq The Sound
One of my all-time favourite songs.
It's the one that got me to listen to
Soundtracks for the Blind,
and might've gotten me into Swans altogether.
I don't quite remember
what order I started listening to things in.
This version of it is great.
I don't think I could choose
between this and the studio recording.
There are just
two ways to enjoy it.
I love how frantic the guitars get
at the height of this track.
.
.It Dq I See Them All Lined Up
This version of the song
is way more harsh
than the version on Soundtracks.
It loses some contrast
between the verses
and the explosions of sound
punctuating them,
it just hits hard
the whole time.
.
.It Dq Yum Yab
An absolute banger.
The drums sound so good on this
and they really get me moving.
The whole thing is delightfully nasty and fun.
.El
.
.Pp
Everything else on the album
is good too,
of course,
I just don't have as much to say.
There's almost two and a half hours of music
on this thing!
.
.Sh AUTHORS
.An june Aq Mt june@causal.agency
.Pp
I want to try writing
about different kinds of things here,
and this is my first attempt
at doing so.
There's more music
I want to write about,
and maybe some other
non-computer topics.
