.Dd October 30, 2021
.Dt NAMES 7
.Os "Causal Agency"
.
.Sh NAME
.Nm Names
.Nd three types
.
.Sh DESCRIPTION
There are (at least) three
different types of names
a person has.
.
.Pp
First, there are normie names.
These are names usually made up
of several words
each of which is capitalized.
Most people have one of these,
but it's possible to have more.
They're names that might appear on
various types of Documents.
A
.Dq legal name
(dubious)
is a normie name,
but normie names need not be
.Dq legal
(dubious).
I list this category first
not because it's more important,
but because it is by far the most boring.
.
.Pp
Next, there are Real Names.
Most people have at least a few
and will probably go through
different ones over time.
Your Real Names are anything people
use to refer to you.
On the internet these are often not capitalized.
Sometimes that is the only distinction
between a Real Name
and a normie name.
.
.Pp
There was a period of time
when I was playing a lot of TF2
and not really leaving my apartment.
I had set my steam name to
.Dq gluten product
(yeah, from that dril tweet)
and I talked in the game's voice chat
quite a bit.
Naturally other Gamers in voice chat
called me
.Dq gluten
and at some point I realized
that over the span of months
I had been refered to as
.Dq gluten
more often than any other name.
So that was a Real Name of mine.
People used it and I responded to it.
.
.Pp
Last, there are the True Names.
The kind of name that knowledge of
gives one power over a person.
I don't think any humans
know their own True Names,
but I do believe they exist.
It's possible that other animals
know theirs.
It's probably best not to know though, right?
I think if I knew mine
I would always worry
about accidentally revealing it.
.
.Sh AUTHORS
.An june Aq Mt june@causal.agency
