.Dd January  8, 2022
.Dt TOPICS 7
.Os "Causal Agency"
.
.Sh NAME
.Nm Topics
.Nd a bit of a mess
.
.Sh DESCRIPTION
Shortly after my last post
I started writing another one
but I never finished it.
I don't think I had enough to say,
or if I did it meant going into
a whole extra thing.
I also had a list in my mind
of other things to write about,
but inspiration hasn't really struck
for any of them.
I'm currently in the mood
to write something anyway,
so I'm just going to write a bit
about the topics I have in mind.
I may or may not ever
write more about any of them.
.
.Pp
The post I had started writing
(twice, actually)
was about voices.
I like them a lot
and I'm fascinated by them.
The problem is
I don't actually have much
to say about it
without getting into Gender,
which as I say is a whole extra thing,
and not something I've written about here before.
.
.Pp
When I started writing here,
I didn't want to blog about
personal topics or LGBTQ stuff.
But more recently
I want to move away from
only writing about computers.
Or maybe away from
writing about computers entirely.
There are more interesting things,
but I don't have experience
writing about them.
Yet,
I should say.
.
.Pp
I'm honestly still not sure
if writing about gender here
is at all a good idea.
But it turns out to feel like
a bit of a prerequisite
for other things.
I find gender perception
in particular
to be fascinating.
It's interesting.
It's neat.
And I don't know if I can
write anything coherent about it.
.
.Pp
Related to that,
I've been thinking of writing
about how the pandemic
has had a strangely positive effect
on my life.
Or at least,
I've made a lot of positive changes
during it.
I'm in a better place emotionally now
than ever before,
and that obviously runs counter
to most people's experiences.
Additionally with that positive outlook
I want to write about the meaning
of my domain name.
I'm proud of it.
.
.Pp
This week the topic of fetish
has been on my mind.
That actually feels
a bit less risky
to write about than gender.
And it may honestly be more interesting.
I don't know.
There's not enough sex
on computer blogs,
or whatever this is.
Although my main ideas
are not about sex at all.
.
.Pp
Just this turned out to be
harder to write than I thought it would be.
I think I want to populate this space
with more short posts like the previous one.
I wrote that while very sleepy
after 3 AM though,
and I don't exactly
want to repeat that regularly.
We'll see.
.
.Sh AUTHORS
.An june Aq Mt june@causal.agency
.Pp
Listening to Kate Bush \(em Hounds of Love.
