.Dd January  8, 2022
.Dt DISCS 7
.Os "Causal Agency"
.
.Sh NAME
.Nm Desert Island Discs
.Nd we're doing three in this one
.
.Sh DESCRIPTION
In typical fashion
I'm going to write about something
completely different instead.
Something short and simple.
I got thinking about this
after reading a little interview thing
this week.
The question is
which three albums would you want to have
if you were stranded on a desert island.
What could you listen to
for the rest of time?
It's surprisingly easy
to take this question very seriously.
.
.Pp
My immediate thought was
.Em Music for 18 Musicians.
I've literally said this about it
in conversation before.
That's an album
I'd want to have on a desert island.
I find it incredibly soothing,
almost hypnotic.
I really do feel like
I could listen to it forever.
And then maybe I could finally determine
which of its eleven sections
is the best.
.
.Pp
My next thought was
.Em Soundtracks for the Blind .
We already know I'm a huge SWANS fan.
Despite what I've written about
.Em Swans Are Dead ,
I instead jumped to SFTB.
I still think that
.Em Dead
has better tunes,
but
.Em Soundtracks
is definitely the better cohesive album.
It has such atmosphere and mood on it.
Like
.Em 18 ,
it's an album that sucks me in.
Also,
either SWANS album
is an economical choice
in this hypothetical
since they're each 2 hours and 20 minutes long.
.
.Pp
Choosing a third album is a lot harder.
There's so much other music I like
and only one slot left.
There's no other single album
that stands out above the rest
like the previous two,
for me.
.Em Wildlife ,
maybe?
Or 
.Em Jane Doe ?
Perhaps a classic like
.Em Aeroplane ,
or a boomer classic like
.Em The Wall .
But would I really want to
listen to any of those
to the exclusion of everything else?
They're too mood-dependent.
.
.Pp
Then I realized the perfect choice
for third album.
.Em Mouth Moods .
A mashup album is the perfect wildcard,
and
.Em Moods
is just fun as hell to listen to.
I get songs from it stuck in my head
instead of the originals.
The final track,
.Em Shit ,
always gets me moving.
It's a masterpiece.
.
.Bl -enum
.It
Steve Reich Ensemble \(em
.Em Music for 18 Musicians
.It
SWANS \(em
.Em Soundtracks for the Blind
.It
Neil Cicierega \(em
.Em Mouth Moods
.El
.
.Sh AUTHORS
.An june Aq Mt june@causal.agency
.Pp
Listening to Steve Reich Ensemble \(em Music for 18 Musicians.
