.Dd January 12, 2022
.Dt BOOKS-2021 7
.Os "Causal Agency"
.
.Sh NAME
.Nm Books 2021
.Nd a review, I guess
.
.Sh DESCRIPTION
In 2021 I read 26 books.
Finished the 26th right on December 31st.
It's not a lot but it's more than last year.
Here are the ones I loved
(in the order I read them).
I will avoid spoilers,
of course.
.
.Ss Network Effect by Martha Wells
I've been reading the
.Em Murderbot Diaries
series for a while.
They're fun stories.
I liked this full-length novel entry a lot.
I guess it felt like it had more room
for the characters to develop.
This is probably when I started
asking my friends if they'd read it
because I wanted to talk about
Murderbot gender vibes.
.Pp
You may like if: you're trans.
.
.Ss The Once and Future Witches by Alix E. Harrow
Um,
it's about witches!
One of them has the same name as me.
Kind of has some similar vibes to
.%T The Future of Another Timeline ,
which was my favourite book I read in 2020.
.Pp
You may like if: you like women.
.
.Ss A Desolation Called Peace by Arkady Martine
I was so excited for this sequel to
.%T A Memory Called Empire ,
another previous favourite
and something I've been wanting more of.
I kinda wish there was more fucking in it though honestly.
.Pp
You may like if: you like women.
.
.Ss Piranesi by Susanna Clarke
Really something different.
It turned out to be a different story
than I expected
from reading the first few pages.
.Pp
You may like if: you like statues, I guess?
.
.Ss A Psalm for the Wild-Built by Becky Chambers
Ok yes I do give 3/3 stars
to every Becky Chambers book.
They're so fucking good.
I'm looking forward to
more entries in this novella series.
(Also I'm currently reading
the fourth
.Em Wayfarers
book
and loving it too!)
.Pp
You may like if: your pronouns are they/them <3
.
.Sh HONOURABLE MENTIONS
.Ss Her Body and Other Parties by Carmen Maria Machado
I really enjoyed the short story
.Dq Especially Heinous: 272 Views of Law & Order SVU
in this collection.
It goes on a bit too long
but the format is unique.
You can read that one online,
actually.
.
.Ss The Hobbit by J. R. R. Tolkien
Yeah I hadn't read this until last year.
I borrowed it after marathoning
the extended editions of the
.%T Lord of the Rings
trilogy during a heat wave.
As I said at the time,
pretty good for something
written by a man
like a hundred years ago.
Kind of hilarious that women
just don't exist
in the world of
.%T The Hobbit .
.
.Ss Earthlings by Sayaka Murata
Pretty fucking wild.
I'd recommend it,
but I have to say it
.Em extremely
needs a child sexual abuse content warning on it.
.
.Ss Six Months, Three Days, Five Others by Charlie Jane Anders
A surprising number of these short stories
are actual stories!
They have beginnings,
middles
and ends!
.
.Ss The City in the Middle of the Night by Charlie Jane Anders
It's got some
.Em Xenogenesis
series vibes.
Sophie is a goddamn lesbian idiot though
and she never even realizes it.
.
.Sh SEE ALSO
.Lk https://git.causal.agency/src/tree/txt/books.txt
.
.Sh AUTHORS
.An june Aq Mt june@causal.agency
.Pp
Listening to
.Em Ear Massage with Latex Gloves 100% Sensitivity 40 minute (No Talking) .
