.Dd January 13, 2022
.Dt ALBUMS-2021 7
.Os "Causal Agency"
.
.Sh NAME
.Nm Albums 2021
.Nd a review
.
.Sh DESCRIPTION
Every year I create a new playlist
in iTunes
(Music dot app, whatever)
for the albums I listen to that year.
It's usually embarrassingly short.
I don't listen to new music
as much as I'd like,
and usually only one or two
are actually from the current year.
Not that the playlist
is limited to new (to me) music.
If I get really into an album
I've heard before,
more than before,
I also add it to the list.
Anyway,
this is a review
of my 2021 albums playlist.
.
.Ss Black Country, New Road \(em For the First Time (2021)
I first heard the single
.Em Sunglasses
from someone sharing it on IRC,
and I loved it,
so I was looking forward to this album.
What a let down though.
The version of
.Em Sunglasses
on the album is just plain worse
than the single version.
I still got some decent listening
out of the album,
but that just sours it for me.
.Pp
Favourite track:
.Em Track X .
.
.Ss Black Dresses \(em Forever \&In Your Heart (2021)
I fucking love Black Dresses.
.Em Peaceful as Hell
is one of my all-time favourite albums.
I'm glad they put out another one
after it looked like they wouldn't.
The sounds are just so good.
Exactly what my ears crave.
The texture of it
tickles my brain clit.
.Pp
Favourite tracks:
.Em Waiting42moro ,
.Em Mistake .
.
.Ss Low \(em Drums and Guns (2007)
I've long loved the song
.Em Breaker
and its music video,
but I only listened to the album
it's on last year.
Something I didn't realize,
I guess because I usually pulled up
the music video
without headphones on,
is how aggressively this album
uses stereo panning.
Vocals are generally
panned hard right throughout,
with much of the instrumentation
panned centre or hard left.
It's bold
and it really works for me.
I especially love the vocal harmony on
.Em Breaker
all the way on the opposite channel.
Bring back stereo separation!
.Pp
Favourite tracks:
.Em Breaker ,
.Em Murderer ,
.Em Violent Past .
.
.Ss The Armed \(em Ultrapop (2021)
I have to admit
I didn't actually listen to this one much.
I listened to the previous album,
.Em Only Love ,
a lot in 2020.
I think this album is good,
but I'll probably only really get into it
in some future year.
.
.Ss Lingua Ignota \(em Caligula (2019)
Dear lord,
why did I wait so long
to listen to this one.
I had heard
.Em "Do You Doubt Me Traitor"
back when it came out,
but somehow I didn't realize
just how much this album
would be my shit.
Fucking incredible vocals.
Lovely sometimes minimal,
sometimes extreme
instrumentals
and exquisite percussion.
The sound of,
I believe,
a lightbulb rolling around on the floor on
.Em Fragrant
is such an interesting addition.
.Pp
Favourite tracks:
.Em "Do You Doubt Me Traitor" ,
.Em "Fragrant Is My Many Flower'd Crown" ,
.Em "If the Poison Won't Take You My Dogs Will" .
.
.Ss Black Dresses \(em LOVE AND AFFECTION FOR STUPID LITTLE BITCHES (2019)
I wanted even more Black Dresses
and fortunately there was still more
I hadn't yet listened to!
I've already gushed about Black Dresses
so I'll spare you.
They're so good though.
.Pp
Favourite tracks:
.Em STATIC ,
.Em HERTZ ,
.Em MY HEART BEATS OUT OF TIME .
.
.Ss Barenaked Ladies \(em All Their Greatest Hits: Disc One 1991-2001
What?
Yeah,
late last year I decided to revisit BNL.
My parents listened to them a lot
when I was growing up,
and I liked them too.
The first show I ever went to was the
.Dq Barenaked for the Holidays
tour with my parents.
It turns out
I still think their '90s stuff
is pretty darn good!
Steven Page is really a great singer.
This is also the first time
I'm listening to these tunes
with fancy headphones
and it sounds great.
Honestly
.Em The Old Apartment
can totally compete
with the favourites
I've accumulated more recently.
\&'90s alt rock was good actually?
.Pp
Favourite tracks:
.Em The Old Apartment ,
.Em Brian Wilson ,
.Em What a Good Boy ,
.Em Too Little Too Late .
.
.Sh AUTHORS
.An june Aq Mt june@causal.agency
.Pp
Listening to all my favourite tracks :)
