.Dd March  5, 2022
.Dt VOICES 7
.Os "Causal Agency"
.
.Sh NAME
.Nm Voices
.Nd more kinds of them
.
.Sh DESCRIPTION
Welcome to the third time
I started writing this post!
I think the first time
was after watching a jan Misali video
that had clips of audio interviews in it.
It got me thinking about
how interesting it was
to hear someone's voice
without knowing anything else about them.
.
.Pp
That's pretty much all I managed to write
the first two times I started this.
If I get past this next sentence,
then I can probably finish the post.
What stopped me was that
all my thoughts and feelings about voices
are influenced by being trans
(and being a fan of other trans people),
and I thought,
.Dq I don't write about that here,
but why don't I?
I don't have to come out to my blog.
.
.Pp
So really what I have been wanting to say is this:
every trans woman's voice that I have heard
has sounded genuinely wonderful to me.
Especially if you're reading this
and we've been on a voice call before.
I know,
voices are the object of so much self-consciousness,
but I really wish they didn't have to be.
Most of us do not sound like cis women
and to me that is fine.
Good, actually.
Trans women sound like trans women.
As a voice appreciator,
I am so happy to hear more kinds.
.
.Sh AUTHORS
.An june Aq Mt june@causal.agency
.Pp
I've been watching some Vektroid streams lately,
and I love her voice.
It was another thing
reminding me to write this.
