.Dd March 18, 2022
.Dt ADDENDUM-2021 7
.Os "Causal Agency"
.
.Sh NAME
.Nm Addendum 2021
.Nd missed music
.
.Sh DESCRIPTION
I just realized that I totally forgot
some important music for me from last year
in my Albums 2021 post,
because it wasn't in my playlist.
Last year I watched
the Berserk anime from 1997,
and its soundtrack is incredible.
.
.Pp
Actually the only reason
I started watching it at all
was because of the music.
I was watching the wayneradiotv stream,
.Do
Mon repas durant un temps de tristesse;
un pizza je n'oublierai jamais
.Dc
and I was mesmerized by the Guts theme.
I had to find out what it was from.
This was also around the time
that Kentaro Miura died
so people were really talking about it.
Anyway just hearing
that part of the soundtrack
got me to start watching the anime,
since you can find it all on youtube.
.
.Pp
The anime in general did not disappoint.
Actually it's really fucking good,
and so is the rest of the soundtrack.
The title sequence and credits tracks
are so good that I let them play
every episode even though
I watched the series over only like 2 days.
.
.Pp
I absolutely love whatever genre this stuff is.
Is '90s anime intros its own genre?
Something about combining
acoustic and electric guitars,
maybe.
I'm also fond of
the poorly written english lyrics.
They're poetic in a distinctive way.
I feel the same about
that Shinsei Kamattechan
song that was used for the credits of
Attack on Titan season 2.
Honestly awesome to write lyrics
in a second language you haven't mastered.
.
.Pp
So,
the intro track,
.Em Tell Me Why .
First off,
that sword sound effect
near the beginning rules.
Put that in more songs.
What I really can't get enough of
on this track are
the quiet shouty vocals
a bit off to the left
during the chorus.
It's such a cool idea
to have clean lead vocals
and shouting in the background.
.
.Pp
And the credits track,
.Em "Waiting So Long" .
That first low note is so good.
This is really a perfect credits song
for the atmosphere of the show.
It's creeping.
The dual vocals
the whole way through
are such an interesting texture.
Both of these tracks
have really cool vocal sounds.
And that dirty final guitar chord
is a great sound to end on.
.
.Sh SEE ALSO
These aren't great quality uploads
but this stuff is sadly hard to find.
.Bl -tag -width Ds
.It "Guts"
.Lk https://youtu.be/vZa0Yh6e7dw
.It "Earth"
.Lk https://youtu.be/5iAViNf9Z4Y
.It "Penpals \(em Tell Me Why"
.Lk https://youtu.be/I2rV8oKWSdM
.It "Silver Fins \(em Waiting So Long"
.Lk https://youtu.be/70GD2SBCq64
.El
.
.Sh AUTHORS
.An june Aq Mt june@causal.agency
.Pp
.Dq I like swinging my sword in battle.
