.Dd March 31, 2022
.Dt COMPASSION 7
.Os "Causal Agency"
.
.Sh NAME
.Nm Compassion
.Nd better world fiction
.
.Sh DESCRIPTION
Recently I watched the film
.Em Margarita With a Straw .
I'm not sure how to feel
about some aspects of it,
but it tries to do a lot,
and I was still thinking about it
a couple days later.
.
.Pp
What really sticks out about it,
to me,
is that it is
better world fiction,
for lack of a better term.
It's a film about two characters
with disabilities,
but it doesn't play into tropes.
There's no big dramatic scene
where a character gets treated unfairly.
It doesn't really happen.
In the world of the movie,
most people are accepting,
patient
and compassionate.
That's not to say
there is no conflict.
The film is just telling a different story.
.
.Pp
The story takes place
in a better world.
Or maybe it takes place
in a world that exists
within our own,
hidden between the worse parts.
It's wonderfully subversive.
Because I went into the film
expecting at least one deeply upsetting
scene of discrimination.
What else would you expect
of a story like this one,
right?
But instead of being upset,
I was warmed.
It was so nice to see
the characters work through
their own problems
surrounded by simple kindness.
And when it was over,
I was left wanting
to move our world
closer to that one.
.
.Pp
That's what I love about this kind of fiction.
It's why I love the books of Becky Chambers so much.
They give me hope,
and guidance.
I count the
.Em Murderbot Diaries
series in this as well,
which shows a sort of bad world,
and an alternative.
I think it's so important
to see the good that exists
and the good that could exist.
Rather than something to fight against,
these stories show something to fight for.
A more compassionate world.
.
.Pp
I know,
one person can't change the world.
But they can change their own world,
and the worlds of those around them.
And slowly,
good things can spread.
I'll strive to be
more patient,
more understanding,
more compassionate,
and I hope you will too.
.
.Sh AUTHORS
.An june Aq Mt june@causal.agency
.
.Pp
I can't help but worry,
when I write something like this,
that someone I know will read it
and think that I'm lying
because I've hurt them.
If that's the case,
I am sorry,
and I promise
I am trying to do better.
