.Dd April  3, 2022
.Dt CARE 7
.Os "Causal Agency"
.
.Sh NAME
.Nm Care
.Nd trans stuff in Montreal
.
.Sh DESCRIPTION
This kind of info
is frustratingly hard to find
even from support orgs
and the like.
I think it's unlikely
that anyone in my blog's audience
is also someone who needs this info,
and my blog isn't easy to find either,
but I want to at least
make it available somewhere.
Really this is just like
the posts where I figure out
how to do something with a computer
then I write it down.
.
.Pp
Prices obviously change,
by which I mean they inevitably go up,
but I'm gonna give the amounts I paid
in 2021\(en2022.
.
.Ss Medication
I get HRT through
Dr. Gabrielle Landry
at La Clinique A,
which is a private clinic.
I've done everything over the phone.
After the first consultation,
I signed an informed consent form
and had a prescription the next day,
which I could start
after I got an initial blood test.
The information I found
said to contact a specific person
at the clinic with a direct phone number,
which is what I did.
Email me if you want that number.
.
.Pp
I paid $300 for the first consult,
$195 for the first followup,
and $75 for further followups.
I think annual appointments
are more expensive
than the followups.
I've been getting blood tests done at a CLSC,
which is free.
On the public drug insurance plan,
I paid $30-$35
for my prescriptions
as my dosage increased.
I have private insurance now
that entirely covers prescriptions,
so I'm not sure what I'd be paying
for my current prescription
on the public plan.
.
.Ss Hair removal
I've gotten laser hair removal treatments
at Dermamode with Audrey.
They're very nice there.
The initial consultation was over the phone.
I paid $1350 for 6 treatments,
in two installments
at the first and second appointments,
plus the ~$200 tax on that
before the first appointment,
I think.
It hasn't gone well for me so far,
but I'm hoping it will
now that my testosterone levels
have dropped.
I will report back.
.
.Ss Sex & name change
The form for this is
.Do
Application to Change the Sex Designation
of a Person 18 Years of Age and Over
.Dc
from the
.Em Directeur de l'\('etat civil .
It's self-ID,
but you have to get it signed by
someone you know
and a commissioner for oaths.
Julien at P10 is qualified for that
and was super nice.
We did it over Zoom.
It's a free service,
so I made a donation to P10.
.
.Pp
I paid $144 to file mine
but it's now $148.
Also $17 to mail it.
Surprisingly,
I got an acknowledgment letter
.Po
just saying they got it
and would start looking at it
.Dq shortly
.Pc
like a week and a half
after I mailed the application.
My cheque was cashed
39 days after the date
on the acknowledgment,
and I got a
.Dq favourable decision
a week later.
It takes another 30 days
to get the certificate of change,
after which you can
order a new birth certificate
and RAMQ will (slowly) send you a form
to get a new card.
In all it took about 4 months
from when I mailed the application
to having ID with my name on it.
.
.Ss Therapy
I'm not seeking therapy
for gender specifically,
but I would like to find a good therapist
that's aware of it.
I'll update this
if I find one.
.
.Ss Piercings
Ok I know this isn't trans-specific
but at least for me getting piercings
was gender-affirming.
And I don't mean like
getting your ears pierced
is some kind of female rite of passage,
because that's not even what I got done.
Anyway,
I went to Mauve.
They're super nice,
really know what they're doing,
and their website has lots of info.
.
.Sh AUTHORS
.An june Aq Mt june@causal.agency
.
.Pp
If somehow you did find this useful,
I'd love for you to email me
and let me know how things went for you.
