.Dd April 14, 2022
.Dt AGENCY 7
.Os "Causal Agency"
.
.Sh NAME
.Nm Agency
.Nd origin of a name
.
.Sh DESCRIPTION
When I registered this domain name,
it was aspirational.
Intentionally so.
I wanted a new domain
for a new identity,
and I was thinking about personhood.
That's what causal agency means.
.
.Pp
It really was aspirational
for me at the time.
I spent a lot of time
wishing I could be a person,
because I didn't feel like one.
I didn't feel real,
like everyone else was.
I didn't have any power
over my own life.
Things just happened to me,
and I watched.
There wasn't really a
.Dq me
there.
The world was something that happened
but that I couldn't interact with.
I felt like that
for most of my life.
.
.Pp
But at some point
I decided that,
even if I wasn't now,
one day I hoped to be an actual real life person.
Like most programmers
I am dreadful at naming things,
so I didn't come up
with this clever domain name
myself.
I typed
.Dq person
into some thesaurus,
and it gave back
.Dq causal agent ,
and I realized
agency is a TLD now.
.
.Pp
Maybe it's a little dramatic
to label myself with the thing
I didn't think I had.
But who knows,
maybe it helped.
Because it took a few years,
but I did become a person.
I feel real now.
I can change my own life
and the world around me.
I have causal agency.
.
.Pp
I am really proud of this domain name.
I'm proud to put it on everything I make.
Every instance of it
is a reminder
that I did what I set out to do,
and that I'm still doing it.
.
.Sh AUTHORS
.An june Aq Mt june@causal.agency
.
.Pp
If anything in this post resonates with you,
I want you to know that,
whatever you think you can't do,
it is possible,
and you'll get there one day.
