.Dd September 19, 2022
.Dt APOLOGIES 7
.Os "Causal Agency"
.
.Sh NAME
.Nm Apologies
.Nd making them
.
.Sh DESCRIPTION
Apologies are very important to me.
Unfortunately
I've only recently realized
how valuable they are.
I've tried to think about
what makes a good apology,
since it's not something
I was ever taught.
This is the advice
I came up with for myself,
on how to apologize.
.
.Bl -enum
.It
Make the apology.
This is the most important part.
If you feel guilty
for something you've done,
or think you might have hurt someone,
apologize.
Even if they don't need an apology,
saying sorry won't hurt.
And start with that.
Literally say
.Dq I'm sorry .
Sometimes people forget that.
.Pp
On the other side,
if you've been hurt by someone,
and you trust them,
let them know.
Give them a chance to apologize.
People don't always realize
they've made a mistake.
.
.It
Explain what you did wrong.
I think it's important
for the other person
to know you understand
how you've messed up.
Really think about this!
It's what will help you learn.
If you know you've hurt someone
but you're not sure why,
you can try asking them.
Take their answer seriously.
.
.It
Don't make excuses.
Do not talk about yourself.
Don't even mention
how you were feeling stressed that day,
or whatever.
It's not relevant.
We all make mistakes,
we all have bad days.
.
.It
Commit to doing better.
Try to learn from your mistakes.
Say it won't happen again.
Literally say
.Dq I won't do that again .
And then try your hardest to make that true.
An apology is a commitment,
not something you're done with
once you've said it.
.El
.
.Sh AUTHORS
.An june Aq Mt june@causal.agency
