.Dd November 14, 2022
.Dt SOUND-MEMORY 7
.Os "Causal Agency"
.
.Sh NAME
.Nm Sound Memory
.Nd associations
.
.Sh DESCRIPTION
.Ss Talking Heads \(em "Remain In Light"
The first time I gave this album a serious listen
was when I was going for several-hour walks
at 4 in the morning in,
I think,
fall 2020.
I would stay up all night,
go out walking at 4am
for a couple hours,
come home,
eat
.Dq breakfast
and go to sleep.
I listened to this album
walking on completely empty
big city streets
in the dark.
.
.Ss Buffy Sainte-Marie \(em Up Where We Belong
I started listening to this album
after hearing it many mornings
walking into the cafe on my block
back in 2019.
I could tell Vincent was working
if I heard this when I opened the door.
.
.Ss Molasses \(em Trilogie: Toil & Peaceful Life
I listened to this when I had 8am classes
in CEGEP.
In particular my first semester philosophy course,
which was in the forum.
I usually got there even earlier
because of how the bus schedules worked out.
There was another girl in my class,
who I always sat next to,
who also got there early,
but we never spoke outside of class.
.
.Ss Arcade Fire \(em Funeral
This album just feels like walking outside
in fresh snow in early winter,
you know?
.
.Ss Molasses \(em Trouble at Jinx Hotel
I listened to this when I was looking for an apartment.
I specifically remember listening to it
walking down Clark toward my new place
to pick up my keys.
.
.Ss Arcade Fire \(em Neon Bible
The song
.Dq "No Cars Go"
is strongly associated for me
with my earliest gender feelings.
It's how I date when I first
started to feel like something was wrong.
The Suburbs was released in 2010,
so I was probably listening to Neon Bible
in 2011.
Ten years between that
and coming out.
.
.Ss "Do Make Say Think" \(em "You You're a History In Rust"
I remember hearing
.Dq "A Tender History In Rust"
for the first time
at the office of my first job.
Me and my coworkers stayed late,
probably on a Friday night,
drinking free tech startup booze.
.
.Ss mewithoutYou \(em It's All Crazy! It's All False! It's All a Dream! It's Alright
I exclusively listened to this album
on a high school trip to Europe.
Every morning when we got on the bus,
I heard
.Dq Every Thought a Thought of You
and every night before bed
I listened to
.Dq The King Beetle on a Coconut Estate .
.
.Ss Arcade Fire \(em The Suburbs
I listened to this album a tonne
when I was playing
Minecraft and Urban Terror
with my online friends
while I was in high school.
In particular I remember
a backyard shed World of Padman map
and the apartments Minecraft world.
.
.Ss Arcade Fire \(em Reflektor
I associate
.Dq Afterlife
with the walk between Laurier metro
and my first job,
in the winter.
Must've just been how the timing worked out
with my commute at the time.
.
.Ss Swans \(em To Be Kind
I listened to this on one of my playthroughs
of Half-Life 2.
In particular I associate
.Dq Bring the Sun / Toussaint L'Ouverture
with the Water Hazard chapter.
.
.Ss Wrekmeister Harmonies \(em Light Falls
For a while I put this on whenever I
left my apartment to go somewhere
and it was already dark,
so probably winter.
.
.Ss St. Vincent \(em MASSEDUCTION
This,
along with the next one,
I think were all I listened to
on a family vacation
to Quebec City and New Brunswick
some years ago.
.
.Ss SOPHIE \(em Oil of Every Pearl's Un-Insides
Many hours on the road
on that family vacation.
Two albums on repeat.
.
.Ss Julia Holter \(em Aviary
This is another album
I listened to when I was taking
walks at 4am.
I wasn't in a good place.
Yet.
.
.Ss Beep Test \(em Laugh Track
A tape from the first act
at one of my favourite shows
I've ever been to,
at La Sotterenea
in Suoni 2019.
I wish I had been out already.
.
.Ss The Armed \(em Only Love
The third of the albums I listened to
on those dark walks.
I listened to it loud,
this album's mixing needs it.
.
.Ss Eliza Kavtion \(em The Rez That Summer
A favourite local artist.
I remember vividly the first time
I heard her play,
opening for Wrekmeister Harmonies
at La Vitrola in 2018.
.
.Sh AUTHORS
.An june Aq Mt june@causal.agency
