.Dd December 21, 2022
.Dt ALBUMS-2022 7
.Os "Causal Agency"
.
.Sh NAME
.Nm albums 2022
.Nd review
.
.Sh DESCRIPTION
it's the year-end review
of albums I listened to.
same as last year,
I added any albums I got into
this year to a playlist.
I've actually done that
every year since 2018.
maybe I'll review
those old playlists some time.
.
.Ss ZHAOZE \(em SUMMER INSECTS TALK ABOUT ICE (2021)
it's a five-and-a-half-minute album!
you can loop it however long you want.
it's really lovely.
.Pp
favourite track:
ON HORSEBACK, TO FARAWAY
.
.Ss KATE BUSH \(em HOUNDS OF LOVE (1985)
first of all I do not watch that one show.
I've known that track for a while actually.
I mean I probably first heard the CHROMATICS cover.
but anyway,
I think someone mentioned this album
on IRC at just the right time
and I put it on.
the second half really shines tbh.
love a concept album.
.Pp
favourite tracks:
RUNNING UP THAT HILL,
HOUNDS OF LOVE,
AND DREAM OF SHEEP,
WATCHING YOU WITHOUT ME,
THE MORNING FOG.
.
.Ss GODSPEED YOU! BLACK EMPEROR \(em ALL LIGHTS FUCKED ON THE HAIRY AMP DROOLING (1994)
didn't expect to hear this probably ever.
still wild that it finally got uploaded.
and to be honest I'm a little mad
that it's actually good.
like yeah it's not a godspeed album
but it holds up as a tape on its own.
it's the kind of shit I listen to.
also can't believe some people
still thought it was fake.
like have you not heard
any other efrim menuck projects?
.Pp
favourite tracks:
$13.13,
DIMINISHING SHINE,
DADMOMDADDY,
333 FRAMES PER SECOND,
ALL ANGELS GONE.
.
.Ss BLACK DRESSES \(em FORGET YOUR OWN FACE (2022)
woops I think I only listened to this like twice.
will need to revisit it later for sure.
I'll like it.
.
.Ss BACKXWASH \(em I LIE HERE BURIED WITH MY RINGS AND MY DRESSES (2021)
only got into this album
after hearing it live this summer.
was the first show I went to in years
and it was really fucking good.
gotta listen to this shit loud.
sampling godspeed for a beat fucks.
honestly back to back bangers.
.Pp
favourite tracks:
I LIE HERE BURIED WITH MY RINGS AND MY DRESSES,
TERROR PACKETS,
SONG OF SINNERS,
BURN TO ASHES.
.
.Ss PHILIP GLASS ENSEMBLE \(em EINSTEIN ON THE BEACH (1979)
actually just the knee plays
because I can't be bothered
listening to all of it.
and I'm embarrassed by how much
I enjoy this avant-garde bullshit.
like ok just sing repeating numbers at me
and my brain is happy.
what is this?
my kink?
anyway I also have kind of an obsession
with the
.Dq story of love
in knee 5.
I fucking hate it.
but it's delivered so well.
and that violin though!
.Pp
favourite tracks:
KNEE 1,
KNEE 5.
.
.Ss KANYE WEST \(em YEEZUS (2013)
ok look I listened to this
before recent events.
what the fuck.
it's a really good album though?
pretty sure I listened to it
because bound 2 kept getting in my head,
because of that minecraft parody parody
wayne did ages ago.
.Pp
favourite tracks:
BLACK SKINHEAD,
HOLD MY LIQUOR,
BLOOD ON THE LEAVES,
BOUND 2.
.
.Ss FLYING RACCOON SUIT \(em AFTERGLOW (2021)
I've listened to the whole album
a few times
but I'm mostly just here
for the title track.
this also happened to be
dropped in IRC at just the right time.
good ska-punk-type shit.
and I like lisps ok.
.Pp
favourite track:
AFTERGLOW.
.
.Ss RAMSHACKLE GLORY \(em LIVE THE DREAM (2011)
one of those albums
I don't know why I took so long
to get to.
I've been listening to johnny hobo
since I was like in high school.
ramshackle is a little more hopeful
and I love that.
your heart is a muscle the size of your fist.
keep on loving.
keep on fighting.
.Pp
favourite tracks:
WE ARE ALL COMPOST IN TRAINING,
NEVER COMING HOME,
YOUR HEART IS A MUSCLE THE SIZE OF YOUR FIST.
.
.Ss LES RALLIZES D\('ENUD\('ES \(em THE OZ TAPES (2022)
a pleasant surprise in someone's playlist.
lately I've been listening to this
in the metro to or from electrolysis.
it's good listening for that.
bold to have two versions
of the same 24-minute song
on the same release.
.Pp
favourite tracks:
A SHADOW ON OUR JOY,
THE LAST ONE_1970 (ver.2).
.
.Ss LINGUA IGNOTA \(em SINNER GET READY (2021)
another I'm only getting into
after hearing it live.
just last sunday actually.
was a good show.
people will go wild
to hear a cover live for real.
.Pp
favourite tracks:
I WHO BEND THE TALL GRASSES,
PENNSYLVANIA FURNACE,
PERPETUAL FLAME OF CENTRALIA.
.
.Sh AUTHORS
.An june Aq Mt june@causal.agency
.Pp
I started writing this
before I saw LINGUA IGNOTA.
good thing I waited.
