.Dd February 23, 2024
.Dt COMFORT-MUSIC 7
.Os "Causal Agency"
.
.Sh NAME
.Nm comfort music
.Nd feel better
.
.Sh DESCRIPTION
it's been a while.
and I'm on almost no sleep
and haven't eaten a real meal
since noon.
which is a state I've written
at least a couple posts in before,
so what better time
to return to what has apparently
become this blog's format:
lists of some music I like.
.
.Pp
this is a list of music that comforts me.
.
.Bl -bullet
.It
knee play 5, from einstein on the beach.
I like the organ and the counting and the cadence of the story.
.It
low \(em words.
and I'm tired.
.It
godspeed you! black emperor \(em storm.
this is like my original comfort music.
been listening to it since I was teenage.
the grooves are worn deep in my mind.
.It
set fire to flames \(em love song for 15 ontario (w/ singing police car).
I like how it ends.
.It
va, from the beginner's guide.
I think that's the whole point.
though maybe it's too sad
to be truly comforting.
.It
undertale, from undertale.
what can I say?
.It
wrekmeister harmonies \(em covered in blood from invisible wounds.
I find quite a bit of the album comforting really.
I'm picking this one because I like the cadence
of the lyrics.
.It
lingua ignota \(em pennsylvania furnace and perpetual flame of centralia.
these are really my go to in recent times.
I like waiting for the next line.
.El
.
.Sh AUTHORS
.An june Aq Mt june@causal.agency
.Pp
I don't think I've said anything
very interesting here.
