.Dd March 24, 2024
.Dt LITTLE-BLESSINGS 7
.Os "Causal Agency"
.
.Sh NAME
.Nm little blessings
.Nd life's
.
.Sh DESCRIPTION
today I went out to go around.
run some errands and do some shopping.
along the way I was given
several of life's little blessings.
.
.Pp
while walking on ste-cath
between berri and complexe desjardins,
there was a somewhat disheveled man
walking in the same direction and singing.
he had a beautiful voice.
he was singing a sad song in french,
and he sung it well and enunciated every word.
.
.Pp
in the mcdonald's at complexe desjardins,
while waiting for my order,
there were what appeared to be
a teenager and her younger brother,
who must have been
looking at the display of
current happy meal toys.
the teenager was playing smash or pass,
to the amusement of the younger one.
they got ice cream
and ate it across the room from me downstairs.
.
.Pp
later,
taking the 24 home from atwater
carrying my new vacuum cleaner,
the bus got lost.
I think the driver missed the stop
and tried to compensate
by turning north onto peel
and stopping there.
but then he had to keep going up peel.
he turned right onto docteur-penfield,
which just brings you further up the mountain.
when it met des pins,
he turned left and pulled over,
asking for guidance over the radio.
we got moving again,
back towards peel.
that's how I ended up
on a 24
.Dq sherbrooke
east,
facing west on des pins.
it was actually quite scenic.
and amusing.
I was in no rush.
.
.Pp
after getting back onto sherbrooke,
the bus had to take another detour,
this one planned.
so my ride on the 24,
which normally only drives on sherbrooke,
ended up going on peel,
docteur-penfield,
des pins,
de bleury,
ren\('e-l\('evesque
and saint-laurent.
it was a very exciting bus trip.
.
.Sh AUTHORS
.An june Aq Mt june@causal.agency
