.Dd October 12, 2024
.Dt FILM-REVIEW 7
.Os "Causal Agency"
.
.Sh NAME
.Nm film review
.Nd stock, that is
.
.Sh DESCRIPTION
this summer I got really into analog photography.
I've tried out a bunch of different film stocks,
thanks to the local photo lab,
and I've
.Em developed
(pun intended)
some preferences.
here they are.
.
.Sh BLACK & WHITE
.Bl -enum
.It
Ilford FP4+ (ISO 125, United Kingdom)
.Pp
definitely my favourite b&w film.
I love the fine grain and contrast
with good shadow detail.
really just exactly what I want
out of a b&w film I think.
ISO 125 is quite generous for what it is,
but it's still best suited for sunny days.
.Pp
sample:
.Lk https://photo.causal.agency/2024-09-29/
.
.It
Fomapan Creative (ISO 200, Czech Republic)
.Pp
I've only shot one roll of this so far,
but I really like the balance it strikes
between fine grain and high speed.
it just seems like a good go-to film
for what I like to do with b&w photography,
given the extra flexibility over FP4.
.Pp
sample:
.Lk https://photo.causal.agency/2024-09-14/
.
.It
Ferrania P30 (ISO 80, Italy)
.Pp
another that I've only shot one roll of,
but I really like the results.
obviously it swings in the other direction
in terms of film sensitivity,
but more importantly
it has a distinctive look.
that's harder in b&w than it is in colour!
.Pp
sample:
.Lk https://photo.causal.agency/2024-10-05/
.
.It
Ilford Delta 100 (United Kingdom)
.Pp
as far as I'm concerned this is just more expensive FP4.
it certainly looks good
but I'd rather save the couple extra dollars.
.Pp
sample:
.Lk https://photo.causal.agency/2024-09-22/
.
.It
Ilford HP5+ (ISO 400, United Kingdom)
.Pp
it's like, ok.
more grainy than I'd like,
but that's to be expected of high speed.
my real problem with it
is the lack of contrast.
maybe I should only be shooting it pushed,
but I don't want to pay the extra fee
to have my local photo lab do that.
.Pp
sample:
.Lk https://photo.causal.agency/2024-09-07/
.
.It
Fomapan Action (ISO 400, Czech Republic)
.Pp
I almost wonder if something went wrong
either in shooting or processing
the one roll of this I shot.
everything came out very low contrast.
.Pp
sample:
I didn't end up uploading any.
.El
.
.Sh COLOUR
.Bl -enum
.It
Shanghai Color (ISO 400, China)
.Pp
I love the desaturated colours
and the grain on this.
I guess I like fine grain in b&w
and coarse grain in colour.
I think this is well suited
to the subjects I like to photograph,
like old brick buildings,
but it also does nature quite nicely.
I think this will be a good one to capture fall with.
.Pp
ok so this is almost certainly repackaged
Wolfen Color NC500
(made in germany).
but the thing is,
shanghai does a better job packaging it.
they use real metal cassettes
and add film edge markings.
and their box design is way nicer.
and on top of THAT,
my local photo lab
sells it for cheaper than NC500.
.Pp
sample:
.Lk https://photo.causal.agency/2024-09-22/
.
.It
Harman Phoenix (ISO 200, United Kingdom)
.Pp
phoenix is a fun film!
the lack of yellow filter
and anti-halation layer
can produce some neat effects.
in the right conditions
it also sometimes looks exceedingly normal.
but it also sometimes just...
doesn't work well.
underexposed areas can get really bad.
apparently it can be better to shoot it at ISO 100.
I should give that a try,
or just be more diligent with
how I'm metering.
.Pp
sample:
.Lk https://photo.causal.agency/2024-08-10/
.
.It
CineStill 800T (USA?)
.Pp
I can't really say much about this yet.
I don't have much experience with indoor photography.
the lack of anti-halation layer
does tend to make lights look sinister as hell, though.
I'll probably shoot
one of the cheaper repackagings
of ISO 800 cinema film
in the future.
.Pp
sample:
.Lk https://photo.causal.agency/2024-10-06/
.
.It
Film Washi
.Dq X
(ISO 100, France)
.Pp
this is mostly pretty normal film
without a yellow filter.
not much to say about it.
I'd be more interested to try washi's
other repackaged b&w technical films,
but I think I missed them being in stock here.
.Pp
sample:
.Lk https://photo.causal.agency/2024-08-23/
.
.It
Fujifilm 400 (Japan?)
.Pp
I shot my two first ever rolls on this.
they were surprisingly good!
the scans did the film dirty though.
that was before I found the good photo lab.
.
.It
Kodak Gold (ISO 200, USA)
.Pp
ok so this is a cheap film, right?
but it's too damn good.
fine grain, accurate colour.
it looks like digital to me,
and that's not what I want.
even fuji has a little more character to it than this.
puts me off kodak.
.Pp
sample:
.Lk https://photo.causal.agency/2024-07-01/
.El
.
.Sh AUTHORS
.An Juniper Aq Mt june@causal.agency
.
.Pp
if you have suggestions
for film stocks I should try,
send me an email.
