.Dd January 14, 2021
.Dt IGP 1
.Os
.
.Sh NAME
.Nm igp
.Nd insane gopher posse
.
.Sh SYNOPSIS
.Nm
.Op Fl h Ar host
.Op Fl p Ar port
.Ar directory
.
.Sh DESCRIPTION
The
.Nm
utility is a simple
Internet Gopher server
which can be started by
.Xr inetd 8 .
It serves directory listings
and files under
.Ar directory .
.
.Pp
The arguments are as follows:
.Bl -tag -width Ds
.It Fl h Ar host
Set the host used in directory listings.
The default is the local host name.
.It Fl p Ar port
Set the port used in directory listeings.
The default is port 70.
.El
.
.Sh STANDARDS
.Rs
.%A B. Alberti
.%A F. Anklesaria
.%A D. Johnson
.%A P. Lindner
.%A M. McCahill
.%A D. Torrey
.%T The Internet Gopher Protocol
.%I IETF
.%R RFC 1436
.%D March 1993
.Re
