.Dd January 15, 2017
.Dt GZBUFFER 3
.Os
.
.Sh NAME
.Nm gzbuffer
.Nd set buffer size
.
.Sh LIBRARY
.Lb libz
.
.Sh SYNOPSIS
.In zlib.h
.Ft int
.Fn gzbuffer "gzFile file" "unsigned size"
.
.Sh DESCRIPTION
Set the internal buffer size
used by this library's functions.
The default buffer size is 8192 bytes.
This function must be called after
.Xr gzopen 3
or
.Xr gzdopen 3 ,
and before any other calls
that read or write the file.
The buffer memory allocation
is always deferred to the first read or write.
Three times that size in buffer space is allocated.
A larger buffer size of,
for example,
64K or 128K bytes
will noticeably increase the speed
of decompression (reading).
.
.Pp
The new buffer size also affects
the maximum length for
.Xr gzprintf 3 .
.
.Sh RETURN VALUES
.Fn gzbuffer
returns 0 on success,
or -1 on failure,
such as being called too late.
.
.Sh SEE ALSO
.Xr gzopen 3 ,
.Xr gzprintf 3
.
.Sh HISTORY
This manual page was converted from
.In zlib.h
to mdoc format by
.An June McEnroe Aq Mt june@causal.agency .
.
.Sh AUTHORS
.An Jean-loup Gailly Aq Mt jloup@gzip.org
.An Mark Adler Aq Mt madler@alumni.caltech.edu
