.Dd January 15, 2017
.Dt GZOFFSET 3
.Os
.
.Sh NAME
.Nm gzoffset
.Nd offset in compressed file
.
.Sh LIBRARY
.Lb libz
.
.Sh SYNOPSIS
.In zlib.h
.Ft z_off_t
.Fn gzoffset "gzFile file"
.
.Sh DESCRIPTION
Returns the current offset
in the file being read or written.
This offset includes
the count of bytes
that precede the gzip stream,
for example when appending
or when using
.Xr gzdopen 3
for reading.
When reading,
the offset does not include
as yet unused buffered input.
This information can be used
for a progress indicator.
.
.Sh RETURN VALUES
On error,
.Fn gzoffset
returns -1.
.
.Sh SEE ALSO
.Xr gzerror 3 ,
.Xr gzopen 3 ,
.Xr gzseek 3
.
.Sh HISTORY
This manual page was converted from
.In zlib.h
to mdoc format by
.An June McEnroe Aq Mt june@causal.agency .
.
.Sh AUTHORS
.An Jean-loup Gailly Aq Mt jloup@gzip.org
.An Mark Adler Aq Mt madler@alumni.caltech.edu
