.Dd February 24, 2021
.Dt PLAN 7
.Os "Causal Agency"
.
.Sh NAME
.Nm plan
.Nd possible future projects
.
.Sh DESCRIPTION
.
.Ss bubger -- mostly works
.Bl -bullet -compact
.It
IMAP mailbox (mailing list) archive generator
.It
export HTML/Atom/mboxrd fragments by UID
.It
assemble fragments into threads using IMAP THREAD
.El
.
.Ss feed reader for IMAP
.Bl -bullet -compact
.It
why use a separate reader
when you already have a mail client?
.It
feeds go into IMAP mailboxes
.It
feed entries turn into internet messages
.It
read/unread state like normal mail
.It
reply or forward feed entries as email
.It
all state in IMAP, easy to cron
.El
